apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mywebapp
  name: mywebapp
spec:
  ports:
  - name: "80"
    nodePort: 30085
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywebapp
  type: NodePort
status:
  loadBalancer: {}