name: Flow CI/CD

on:
  pull_request:
    types:
      - "opened"
    branches:    
      - main

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kushwap1/mywebapp:latest  # Please change the username here.

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
# Parse

      - name: Parse log and summarize
        env:
          OPENAI_SECRET_KEY: ${{ secrets.OPENAI_SECRET_KEY }}
        run: |
          pip install openai | tee log.txt
          python3 openai.py log.txt


